"use client";

/* eslint-disable */

import { useState, useEffect } from "react";
import Link from "next/link";

import type { SynthesisOutput, Source, KeyInsight, Opportunity, Risk } from "@/lib/research/synthesis-parser";
import { parseSynthesis } from "@/lib/research/synthesis-parser";

interface ResearchRun {
  id: string;
  query: string;
  keywords: string[];
  result: string;
  sources?: Source[];
  provider: string;
  model: string;
  createdAt: number;
  durationMs: number;
  status: "completed" | "failed";
  error?: string;
}

function formatTime(ts: number): string {
  return new Date(ts).toLocaleString();
}

function formatDuration(ms: number): string {
  if (ms < 1000) return ms + "ms";
  if (ms < 60000) return (ms / 1000).toFixed(1) + "s";
  return Math.floor(ms / 60000) + "m " + Math.floor((ms % 60000) / 1000) + "s";
}



function ConfidenceBadge({ level }: { level: string }) {
  const cls = `confidence-badge confidence-${level}`;
  return <span className={cls}>{level} confidence</span>;
}

function ScoreBar({ label, value, color }: { label: string; value: number; color: string }) {
  return (
    <div className="score-bar">
      <div className="score-bar-header">
        <span className="score-bar-label">{label}</span>
        <span className="score-bar-value" style={{ color }}>{value}/100</span>
      </div>
      <div className="score-bar-track">
        <div className="score-bar-fill" style={{ width: `${value}%`, background: color }} />
      </div>
    </div>
  );
}

export default function ResearchDetailPage({ params }: { params: { id: string } }) {
  const [run, setRun] = useState<ResearchRun | null>(null);
  const [synthesis, setSynthesis] = useState<SynthesisOutput | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showRaw, setShowRaw] = useState(false);

async function loadRun() {
    try {
      const res = await fetch(`/api/research/runs/${params.id}`);
      if (!res.ok) {
        if (res.status === 404) {
          throw new Error("Research run not found. It may have expired or been deleted.");
        }
        throw new Error(`HTTP ${res.status}`);
      }
      const data = await res.json();
      setRun(data);
      const parsed = parseSynthesis(data.result);
      setSynthesis(parsed);
      setError(null);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Failed to load");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadRun();
  }, [params.id]);

  

  async function handleExport(format: "md" | "json") {
    if (!run) return;
    
    let content = "";
    let filename = `research-${run.id.slice(0, 8)}`;

    if (format === "md") {
      content = buildMarkdown(run, synthesis);
      filename += ".md";
    } else {
      content = JSON.stringify(run, null, 2);
      filename += ".json";
    }

    const blob = new Blob([content], { type: format === "md" ? "text/markdown" : "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  }

  function buildMarkdown(r: ResearchRun, s: SynthesisOutput | null): string {
    const lines: string[] = [];
    lines.push("# " + r.query);
    lines.push("");
    lines.push(`*Generated by ${r.provider} / ${r.model} on ${formatTime(r.createdAt)} — ${formatDuration(r.durationMs)}*`);
    lines.push("");
    
    if (r.keywords.length) {
      lines.push("**Keywords:** " + r.keywords.join(", "));
      lines.push("");
    }

    if (s) {
      lines.push("## Executive Summary");
      lines.push("");
      lines.push(s.execSummary);
      lines.push("");

      lines.push("## Scores");
      lines.push("");
      lines.push(`- **Opportunity Score:** ${s.opportunityScore}/100`);
      lines.push(`- **Risk Score:** ${s.riskScore}/100`);
      lines.push("");

      lines.push("## Key Insights");
      lines.push("");
      s.keyInsights.forEach((insight, i) => {
        lines.push(`${i + 1}. ${insight.insight} _(${insight.confidence} confidence)_`);
      });
      lines.push("");

      lines.push("## Top Opportunities");
      lines.push("");
      s.topThreeOpportunities.forEach((opp, i) => {
        lines.push(`### ${i + 1}. ${opp.title}`);
        lines.push("");
        lines.push(opp.description);
        lines.push("");
        lines.push(`*Rationale:* ${opp.rationale}`);
        lines.push("");
      });

      lines.push("## Top Risks");
      lines.push("");
      s.topThreeRisks.forEach((risk, i) => {
        lines.push(`### ${i + 1}. ${risk.title}`);
        lines.push("");
        lines.push(risk.description);
        lines.push("");
        lines.push(`*Mitigation:* ${risk.mitigation}`);
        lines.push("");
      });

      lines.push("## Recommended Next Step");
      lines.push("");
      lines.push(s.recommendedNextStep);
      lines.push("");

      if (s.citations && s.citations.length) {
        lines.push("## Sources");
        lines.push("");
        s.citations.forEach((c, i) => {
          lines.push(`${i + 1}. [${c.title}](${c.url})`);
        });
        lines.push("");
      }
    } else {
      lines.push("## Result");
      lines.push("");
      lines.push(r.result || "*No result*");
      lines.push("");
    }

    return lines.join("\n");
  }

  if (loading) {
    return (
      <div className="research-detail">
        <div className="research-detail-inner">
          <p className="loading">Loading...</p>
        </div>
      </div>
    );
  }

  if (error && !run) {
    return (
      <div className="research-detail">
        <div className="research-detail-inner">
          <div className="error-banner">{error}</div>
          <p><Link href="/history">← Back to history</Link></p>
          <p><Link href="/">← Back to studio</Link></p>
        </div>
      </div>
    );
  }

  return (
    <div className="research-detail">
      <header className="research-detail-header">
        <div className="research-detail-header-inner">
          <Link href="/history" className="research-back-link">← History</Link>
          <h1 className="research-detail-title">{run?.query}</h1>
          <div className="research-detail-meta">
            <span className={`research-status research-status-${run?.status}`}>
              {run?.status}
            </span>
            <span className="research-provider">{run?.provider} / {run?.model}</span>
            <span className="research-time">{run ? formatTime(run.createdAt) : ""}</span>
            <span className="research-duration">{run ? formatDuration(run.durationMs) : ""}</span>
            <button onClick={() => handleExport("md")} className="research-export-btn">
              Export MD
            </button>
            <button onClick={() => handleExport("json")} className="research-export-btn">
              Export JSON
            </button>
          </div>
          {run?.keywords.length ? (
            <div className="research-keywords">
              {run.keywords.map((kw) => (
                <span key={kw} className="research-keyword">{kw}</span>
              ))}
            </div>
          ) : null}
        </div>
      </header>

      <main className="research-detail-main">
        {run?.status === "failed" && run.error && (
          <div className="research-error">
            <strong>Error:</strong> {run.error}
          </div>
        )}

        {synthesis && (
          <>
            <section className="research-section">
              <h2>Executive Summary</h2>
              <p className="research-exec-summary">{synthesis.execSummary}</p>
            </section>

            <section className="research-section research-scores-section">
              <h2>Scores</h2>
              <div className="research-scores-grid">
                <ScoreBar label="Opportunity" value={synthesis.opportunityScore} color="#4ade80" />
                <ScoreBar label="Risk" value={synthesis.riskScore} color="#f87171" />
              </div>
            </section>

            <section className="research-section">
              <h2>Key Insights ({synthesis.keyInsights.length})</h2>
              <div className="research-insights">
                {synthesis.keyInsights.map((insight, i) => (
                  <div key={i} className="research-insight-item">
                    <div className="research-insight-header">
                      <span className="research-insight-number">{i + 1}</span>
                      <ConfidenceBadge level={insight.confidence} />
                    </div>
                    <p className="research-insight-text">{insight.insight}</p>
                    {insight.supportingAgents.length > 0 && (
                      <div className="research-insight-agents">
                        Agents: {insight.supportingAgents.join(", ")}
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </section>

            <section className="research-section">
              <h2>Top Opportunities</h2>
              <div className="research-cards">
                {synthesis.topThreeOpportunities.map((opp, i) => (
                  <div key={i} className="research-card research-card-opportunity">
                    <div className="research-card-header">
                      <span className="research-card-number">{i + 1}</span>
                      <h3 className="research-card-title">{opp.title}</h3>
                    </div>
                    <p className="research-card-desc">{opp.description}</p>
                    <div className="research-card-rationale">
                      <strong>Rationale:</strong> {opp.rationale}
                    </div>
                  </div>
                ))}
              </div>
            </section>

            <section className="research-section">
              <h2>Top Risks</h2>
              <div className="research-cards">
                {synthesis.topThreeRisks.map((risk, i) => (
                  <div key={i} className="research-card research-card-risk">
                    <div className="research-card-header">
                      <span className="research-card-number">{i + 1}</span>
                      <h3 className="research-card-title">{risk.title}</h3>
                    </div>
                    <p className="research-card-desc">{risk.description}</p>
                    <div className="research-card-mitigation">
                      <strong>Mitigation:</strong> {risk.mitigation}
                    </div>
                  </div>
                ))}
              </div>
            </section>

            <section className="research-section">
              <h2>Recommended Next Step</h2>
              <div className="research-next-step">
                {synthesis.recommendedNextStep}
              </div>
            </section>

            {synthesis.citations && synthesis.citations.length > 0 && (
              <section className="research-section">
                <h2>Sources ({synthesis.citations.length})</h2>
                <ul className="research-sources">
                  {synthesis.citations.map((s, i) => (
                    <li key={i} className="research-source-item">
                      <a href={s.url} target="_blank" rel="noopener noreferrer" className="research-source-title">
                        {s.title}
                      </a>
                      {s.snippet && <p className="research-source-snippet">{s.snippet}</p>}
                    </li>
                  ))}
                </ul>
              </section>
            )}
          </>
        )}

        {!synthesis && run?.result && (
          <section className="research-section">
            <h2>Result</h2>
            <div className="research-result">
              <pre className="research-result-text">{run.result}</pre>
            </div>
          </section>
        )}

        <section className="research-section">
          <button onClick={() => setShowRaw(!showRaw)} className="research-toggle-btn">
            {showRaw ? "Hide" : "Show"} raw output
          </button>
          {showRaw && (
            <div className="research-raw-output">
              <pre>{run?.result}</pre>
            </div>
          )}
        </section>
      </main>
    </div>
  );
}
