"use client";

/* eslint-disable */



import { useState, useEffect } from "react";
import Link from "next/link";

interface ResearchRun {
  id: string;
  query: string;
  keywords: string[];
  result: string;
  sources?: Array<{ title: string; url: string; snippet?: string }>;
  provider: string;
  model: string;
  createdAt: number;
  durationMs: number;
  status: "completed" | "failed";
  error?: string;
}

function formatTime(ts: number): string {
  return new Date(ts).toLocaleString();
}

function formatDuration(ms: number): string {
  if (ms < 1000) return ms + "ms";
  if (ms < 60000) return (ms / 1000).toFixed(1) + "s";
  return Math.floor(ms / 60000) + "m " + Math.floor((ms % 60000) / 1000) + "s";
}

export default function ResearchDetailPage({ params }: { params: { id: string } }) {
  const [run, setRun] = useState<ResearchRun | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  async function loadRun() {
    try {
      const res = await fetch(`/api/research/runs/${params.id}`);
      if (!res.ok) {
        if (res.status === 404) {
          throw new Error("Research run not found. It may have expired or been deleted.");
        }
        throw new Error(`HTTP ${res.status}`);
      }
      const data = await res.json();
      setRun(data);
      setError(null);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Failed to load");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadRun();
  }, [params.id]);

  useEffect(() => {
    async function loadRun() {
      try {
        const res = await fetch(`/api/research/runs/${params.id}`);
        if (!res.ok) {
          if (res.status === 404) {
            throw new Error("Research run not found. It may have expired or been deleted.");
          }
          throw new Error(`HTTP ${res.status}`);
        }
        const data = await res.json();
        setRun(data);
        setError(null);
      } catch (e: unknown) {
        setError(e instanceof Error ? e.message : "Failed to load");
      } finally {
        setLoading(false);
      }
    }
    loadRun();
  }, [params.id]);

  async function handleExport() {
    if (!run) return;
    const content = buildMarkdown(run);
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `research-${run.id.slice(0, 8)}.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function buildMarkdown(r: ResearchRun): string {
    const lines: string[] = [];
    lines.push("# " + r.query);
    lines.push("");
    lines.push(`*Generated by ${r.provider} / ${r.model} on ${formatTime(r.createdAt)} — ${formatDuration(r.durationMs)}*`);
    lines.push("");
    if (r.keywords.length) {
      lines.push("**Keywords:** " + r.keywords.join(", "));
      lines.push("");
    }
    if (r.sources && r.sources.length) {
      lines.push("## Sources");
      lines.push("");
      r.sources.forEach((s, i) => {
        lines.push(`${i + 1}. [${s.title}](${s.url})`);
      });
      lines.push("");
    }
    lines.push("## Result");
    lines.push("");
    lines.push(r.result || "*No result*");
    lines.push("");
    return lines.join("\n");
  }

  if (loading) {
    return (
      <div className="research-detail">
        <div className="research-detail-inner">
          <p className="loading">Loading...</p>
        </div>
      </div>
    );
  }

  if (error && !run) {
    return (
      <div className="research-detail">
        <div className="research-detail-inner">
          <div className="error-banner">{error}</div>
          <p><Link href="/history">← Back to history</Link></p>
          <p><Link href="/">← Back to studio</Link></p>
        </div>
      </div>
    );
  }

  return (
    <div className="research-detail">
      <header className="research-detail-header">
        <div className="research-detail-header-inner">
          <Link href="/history" className="research-back-link">← History</Link>
          <h1 className="research-detail-title">{run?.query}</h1>
          <div className="research-detail-meta">
            <span className={`research-status research-status-${run?.status}`}>
              {run?.status}
            </span>
            <span className="research-provider">{run?.provider} / {run?.model}</span>
            <span className="research-time">{run ? formatTime(run.createdAt) : ""}</span>
            <span className="research-duration">{run ? formatDuration(run.durationMs) : ""}</span>
            <button onClick={handleExport} className="research-export-btn">
              Export MD
            </button>
          </div>
          {run?.keywords.length ? (
            <div className="research-keywords">
              {run.keywords.map((kw) => (
                <span key={kw} className="research-keyword">{kw}</span>
              ))}
            </div>
          ) : null}
        </div>
      </header>

      <main className="research-detail-main">
        {run?.status === "failed" && run.error && (
          <div className="research-error">
            <strong>Error:</strong> {run.error}
          </div>
        )}

        {run?.sources && run.sources.length > 0 && (
          <section className="research-section">
            <h2>Sources ({run.sources.length})</h2>
            <ul className="research-sources">
              {run.sources.map((s, i) => (
                <li key={i} className="research-source-item">
                  <a href={s.url} target="_blank" rel="noopener noreferrer" className="research-source-title">
                    {s.title}
                  </a>
                  {s.snippet && <p className="research-source-snippet">{s.snippet}</p>}
                </li>
              ))}
            </ul>
          </section>
        )}

        <section className="research-section">
          <h2>Result</h2>
          <div className="research-result">
            {run?.result ? (
              <pre className="research-result-text">{run.result}</pre>
            ) : (
              <p className="research-empty">No result text available.</p>
            )}
          </div>
        </section>
      </main>
    </div>
  );
}
