"use client";

import { useState } from "react";
import type { AgentId, AgentOutput } from "@/lib/schema/research-schema";

interface ExportActionsProps {
  sessionId: string;
  outputs: Record<AgentId, AgentOutput | null>;
}

export function ExportActions({ sessionId, outputs }: ExportActionsProps) {
  const [copied, setCopied] = useState<string | null>(null);

  const generateMarkdown = (): string => {
    let md = "# Market Research Report\n\n";
    md += "Generated by LaunchLens Research Studio\n\n";
    md += `Session ID: ${sessionId}\n\n`;
    md += "---\n\n";
    for (const agentId of Object.keys(outputs) as AgentId[]) {
      const output = outputs[agentId];
      if (!output) continue;
      const agentName = agentId.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(" ");
      md += `## ${agentName}\n\n`;
      md += `**Summary:** ${(output as any).summary || ""}\n\n`;
      if (agentId === "market-sizer") {
        const o = output as any;
        md += "### Market Size\n\n";
        md += `- TAM: $${o.marketSize.tam.toLocaleString()}\n`;
        md += `- SAM: $${o.marketSize.sam.toLocaleString()}\n`;
        md += `- SOM (3yr): $${o.marketSize.som.toLocaleString()}\n`;
        md += `- Growth: ${o.marketSize.growthRate}%/year (${o.marketSize.growthTrend})\n\n`;
      }
      if (agentId === "synthesis") {
        const o = output as any;
        md += `### Opportunity Score: ${o.opportunityScore}/100\n`;
        md += `### Risk Score: ${o.riskScore}/100\n\n`;
        md += "### Top 3 Opportunities\n\n";
        o.topThreeOpportunities.forEach((opp: any, i: number) => {
          md += `${i + 1}. **${opp.title}** — ${opp.description}\n`;
        });
        md += "\n### Top 3 Risks\n\n";
        o.topThreeRisks.forEach((risk: any, i: number) => {
          md += `${i + 1}. **${risk.title}** — ${risk.description}\n`;
        });
        md += `\n### Recommended Next Step\n\n${o.recommendedNextStep}\n\n`;
      }
      md += "---\n\n";
    }
    return md;
  };

  const generateJSON = (): string => {
    return JSON.stringify({
      sessionId,
      generatedAt: new Date().toISOString(),
      outputs: Object.fromEntries(
        Object.entries(outputs).filter(([_, v]) => v !== null)
      ),
    }, null, 2);
  };

  const copyToClipboard = async (text: string, type: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(type);
      setTimeout(() => setCopied(null), 2000);
    } catch (err) { console.error("Copy failed:", err); }
  };

  const downloadFile = (content: string, filename: string, type: string) => {
    const blob = new Blob([content], { type });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = filename;
    document.body.appendChild(a); a.click();
    document.body.removeChild(a); URL.revokeObjectURL(url);
  };

  const handleExportMarkdown = () => {
    downloadFile(generateMarkdown(), `research-report-${sessionId.slice(0, 8)}.md`, "text/markdown");
  };

  const handleExportJSON = () => {
    downloadFile(generateJSON(), `research-report-${sessionId.slice(0, 8)}.json`, "application/json");
  };

  const handleCopyBrief = () => {
    const synth = outputs["synthesis"] as any;
    if (synth?.launchlensBrief) copyToClipboard(synth.launchlensBrief, "brief");
  };

  return (
    <div className="bg-white rounded-2xl border border-slate-200 p-4 shadow-sm">
      <h3 className="font-semibold text-slate-800 mb-3">Export & Actions</h3>
      <div className="space-y-2">
        <button onClick={handleExportMarkdown}
          className="w-full py-2 px-3 text-sm font-medium bg-slate-50 hover:bg-slate-100 text-slate-700 rounded-lg transition-colors text-left flex items-center gap-2">
          📄 <span>Export as Markdown</span>
        </button>
        <button onClick={handleExportJSON}
          className="w-full py-2 px-3 text-sm font-medium bg-slate-50 hover:bg-slate-100 text-slate-700 rounded-lg transition-colors text-left flex items-center gap-2">
          📦 <span>Export as JSON</span>
        </button>
        <button onClick={handleCopyBrief}
          className="w-full py-2 px-3 text-sm font-medium bg-indigo-50 hover:bg-indigo-100 text-indigo-700 rounded-lg transition-colors text-left flex items-center gap-2">
          {copied === "brief" ? "✅" : "📋"} <span>{copied === "brief" ? "Copied!" : "Copy LaunchLens brief"}</span>
        </button>
      </div>
    </div>
  );
}
